language: node_js

node_js:
  - node
  - lts/erbium

branches:
  only:
    - master

env: >
  NODE_ENV=test
  APP_NAME='Express API ES6 Starter'
  APP_VERSION='1.0.0'
  TEST_APP_PORT='9945'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - yarn test:coverage

after_script:
  - yarn codecov
