export const SERIAL_INPUT = 'SERIAL_INPUT';
export const SERIAL_OUTPUT = 'SERIAL_OUTPUT';
export const SERIAL_PORT_OPEN = 'SERIAL_PORT_OPEN';
export const SERIAL_WRITE_FAIL = 'SERIAL_WRITE_FAIL';
export const SERIAL_WRITE_SUCCESS = 'SERIAL_WRITE_SUCCESS';
