export const RIGHT_SERIAL_INPUT = 'RIGHT_SERIAL_INPUT';
export const RIGHT_SERIAL_OUTPUT = 'RIGHT_SERIAL_OUTPUT';
export const RIGHT_SERIAL_PORT_OPEN = 'RIGHT_SERIAL_PORT_OPEN';
export const RIGHT_SERIAL_WRITE_FAIL = 'RIGHT_SERIAL_WRITE_FAIL';
export const RIGHT_SERIAL_WRITE_SUCCESS = 'RIGHT_SERIAL_WRITE_SUCCESS';

export const LEFT_SERIAL_INPUT = 'LEFT_SERIAL_INPUT';
export const LEFT_SERIAL_OUTPUT = 'LEFT_SERIAL_OUTPUT';
export const LEFT_SERIAL_PORT_OPEN = 'LEFT_SERIAL_PORT_OPEN';
export const LEFT_SERIAL_WRITE_FAIL = 'LEFT_SERIAL_WRITE_FAIL';
export const LEFT_SERIAL_WRITE_SUCCESS = 'LEFT_SERIAL_WRITE_SUCCESS';
